# Starting point:
# https://www.totaltypescript.com/how-to-create-an-npm-package#6-set-up-our-ci-with-github-actions
name: CI

# Run on ALL pull requests and main
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Run CI
        run: npm run ci
